//! Build script for the runtime-v8 crate.
//!
//! Selects and validates kind/profile/platform-bound V8 startup snapshots.
//! Host and Worker artifacts have independent cfg/env outputs and can never be
//! substituted for one another.
//!
//! # Why per-(os, arch)
//!
//! A V8 startup snapshot serializes a live V8 heap, so it is bound to the
//! target **platform (OS + CPU arch)**: an android-aarch64 snapshot only loads
//! in an android-aarch64 V8, a linux-x86_64 snapshot only in a linux-x86_64 V8,
//! and neither loads in the other even when `CARGO_CFG_TARGET_ARCH` agrees —
//! each OS links a distinct V8 archive (see `v8_target_dir` below), so "same
//! arch" is not "same V8". Therefore:
//!
//!   * We keep one snapshot per product, OS and arch under
//!     `snapshots/SNAPSHOT-<profile>-<os>-<arch>.bin` and pick the one matching
//!     `(CARGO_CFG_TARGET_OS, CARGO_CFG_TARGET_ENV, CARGO_CFG_TARGET_ARCH)`.
//!     This makes a single multi-ABI `build-aar.sh` invocation embed the
//!     *correct* snapshot into each `.so` (embedding the wrong one would crash
//!     at startup with a V8 magic-number mismatch, which is also why the
//!     `v8_archive_sha256` recorded in the manifest is checked against the
//!     actual archive on this OS, not just the arch word).
//!   * We only embed for the OS/env combinations `v8_target_dir` recognizes
//!     (android, linux-gnu, OpenHarmony, windows-msvc). Any other host
//!     (`cargo test` on macOS, an unlisted env) always loads extension JS from
//!     source — embedding a foreign-platform snapshot would crash on load.
//!
//! Snapshots are generated by `migo-snapshot-gen` cross-compiled to the target
//! platform and run there (device/emulator for Android and OpenHarmony,
//! natively for Linux and Windows); see `tools/snapshot-gen`.

use std::{
    fs,
    path::{Path, PathBuf},
};

use serde_json::Value;

// The snapshot-input fingerprint helpers are shared verbatim with the
// regression test (`src/tests/snapshot_fingerprint.rs`) so the compile-time
// embed decision and the test agree byte-for-byte. They also mirror
// `scripts/lib/snapshot-fingerprint.sh` (filesystem walk + LC_ALL=C byte order).
mod build_snapshot {
    include!("build_snapshot.rs");
}
use build_snapshot::{
    ManifestIdentity, SNAPSHOT_SCHEMA_VERSION, SnapshotIdentity, collect_js_files,
    collect_rust_files, require_materialized_size, sha256_file, snapshot_feature_hash,
    snapshot_js_hash, snapshot_profile_features, snapshot_runtime_hash, validate_snapshot_identity,
};

fn main() {
    // Declare custom cfg for check-cfg lint.
    println!("cargo::rustc-check-cfg=cfg(migo_has_snapshot)");
    println!("cargo::rustc-check-cfg=cfg(migo_has_worker_snapshot)");
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_PROFILE_FULL");
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_PROFILE_SLIM");
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_WORKER_SNAPSHOT");
    println!("cargo:rerun-if-env-changed=RUSTY_V8_ARCHIVE");

    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let target_env = std::env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();
    let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let profile = std::env::var("PROFILE").unwrap_or_default();
    let product_profile = match selected_product_profile() {
        Ok(profile) => profile,
        Err(reason) => {
            println!("cargo:warning={reason}; loading JS from source");
            return;
        }
    };

    // The OS word used in snapshot filenames, and the directory under
    // engine/third_party/rusty_v8/ that names this platform's V8 archive.
    // `target_os` alone cannot distinguish Linux from OpenHarmony — Rust
    // reports both as `target_os = "linux"` with `target_env` carrying "ohos"
    // — so both are consulted. Anything else (macOS, an unlisted env) has no
    // committed V8 archive to embed against and always loads JS from source.
    let (os_word, v8_target_dir) = match (target_os.as_str(), target_env.as_str()) {
        ("android", _) => ("android", format!("{target_arch}-linux-android")),
        ("linux", "ohos") => ("ohos", format!("{target_arch}-linux-ohos")),
        ("linux", _) => ("linux", format!("{target_arch}-linux-gnu")),
        ("windows", _) => ("windows", format!("{target_arch}-pc-windows-msvc")),
        _ => return,
    };

    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir
        .ancestors()
        .nth(3)
        .expect("runtime-v8 must live under <repo>/engine/crates");
    let cargo_lock = repo_root.join("engine/Cargo.lock");
    let v8_archive = std::env::var_os("RUSTY_V8_ARCHIVE")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            repo_root
                .join("engine/third_party/rusty_v8")
                .join(&v8_target_dir)
                .join("librusty_v8.a")
        });
    let snapshot_path = manifest_dir.join("snapshots").join(format!(
        "SNAPSHOT-{product_profile}-{os_word}-{target_arch}.bin"
    ));
    let snapshot_manifest = PathBuf::from(format!("{}.manifest.json", snapshot_path.display()));
    let worker_snapshot_path = manifest_dir.join("snapshots").join(format!(
        "SNAPSHOT-worker-{product_profile}-{os_word}-{target_arch}.bin"
    ));
    let worker_snapshot_manifest =
        PathBuf::from(format!("{}.manifest.json", worker_snapshot_path.display()));

    // Re-run if the snapshot or any input covered by its fingerprint changes.
    // Watching the directory recursively also catches newly-added JS files;
    // the per-file entries below keep ordinary content changes explicit.
    println!("cargo:rerun-if-changed={}", manifest_dir.display());
    println!("cargo:rerun-if-changed={}", snapshot_path.display());
    println!("cargo:rerun-if-changed={}", snapshot_manifest.display());
    println!("cargo:rerun-if-changed={}", worker_snapshot_path.display());
    println!(
        "cargo:rerun-if-changed={}",
        worker_snapshot_manifest.display()
    );
    println!("cargo:rerun-if-changed={}", cargo_lock.display());
    println!("cargo:rerun-if-changed={}", v8_archive.display());

    // Enumerate extension JS. On ANY error, fail safe: a partial set could
    // hash-match a stale manifest and wrongly accept an outdated snapshot, so
    // never validate/embed here — load JS from source instead. The directory
    // watch above still re-triggers the build once the tree is readable again.
    let js_files = match collect_js_files(manifest_dir) {
        Ok(files) => files,
        Err(error) => {
            println!(
                "cargo:warning=Failed to enumerate snapshot JS inputs: {error}; loading JS from source"
            );
            return;
        }
    };
    for path in &js_files {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    let rust_files = match collect_rust_files(manifest_dir) {
        Ok(files) => files,
        Err(error) => {
            println!(
                "cargo:warning=Failed to enumerate snapshot Rust inputs: {error}; loading JS from source"
            );
            return;
        }
    };
    for path in &rust_files {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    if snapshot_path.exists() {
        match validate_snapshot(
            repo_root,
            &snapshot_path,
            &snapshot_manifest,
            &cargo_lock,
            &js_files,
            &rust_files,
            &v8_archive,
            "host",
            product_profile,
            &target_arch,
        ) {
            Ok(()) => {
                println!("cargo:rustc-cfg=migo_has_snapshot");
                // Absolute path consumed by `include_bytes!(env!("MIGO_SNAPSHOT_PATH"))`.
                println!(
                    "cargo:rustc-env=MIGO_SNAPSHOT_PATH={}",
                    snapshot_path.display()
                );
                println!(
                    "cargo:warning=Validated V8 snapshot for {}-{} ({} bytes), embedding into binary",
                    product_profile,
                    target_arch,
                    fs::metadata(&snapshot_path).map(|m| m.len()).unwrap_or(0)
                );
            }
            Err(reason) => {
                println!(
                    "cargo:warning=Ignoring stale or invalid V8 snapshot for {product_profile}-{target_arch}: {reason}; loading JS from source"
                );
            }
        }
    } else if profile == "release" {
        println!(
            "cargo:warning=No V8 snapshot for {product_profile}-{target_arch} at {} — release build will load JS from source (slower cold start)",
            snapshot_path.display()
        );
    }

    if std::env::var_os("CARGO_FEATURE_WORKER_SNAPSHOT").is_some() {
        if product_profile != "full" {
            println!(
                "cargo:warning=Worker snapshots require profile-full; explicit selection will fail closed"
            );
            return;
        }
        if worker_snapshot_path.exists() {
            match validate_snapshot(
                repo_root,
                &worker_snapshot_path,
                &worker_snapshot_manifest,
                &cargo_lock,
                &js_files,
                &rust_files,
                &v8_archive,
                "worker",
                product_profile,
                &target_arch,
            ) {
                Ok(()) => {
                    println!("cargo:rustc-cfg=migo_has_worker_snapshot");
                    println!(
                        "cargo:rustc-env=MIGO_WORKER_SNAPSHOT_PATH={}",
                        worker_snapshot_path.display()
                    );
                    println!(
                        "cargo:warning=Validated Worker V8 snapshot for {}-{} ({} bytes), embedding into opt-in binary",
                        product_profile,
                        target_arch,
                        fs::metadata(&worker_snapshot_path)
                            .map(|metadata| metadata.len())
                            .unwrap_or(0)
                    );
                }
                Err(reason) => println!(
                    "cargo:warning=Worker snapshot for {product_profile}-{target_arch} is stale or invalid: {reason}; explicit selection will fail closed"
                ),
            }
        } else {
            println!(
                "cargo:warning=No Worker V8 snapshot for {product_profile}-{target_arch} at {}; explicit selection will fail closed",
                worker_snapshot_path.display()
            );
        }
    }
}

fn validate_snapshot(
    repo_root: &Path,
    snapshot_path: &Path,
    manifest_path: &Path,
    cargo_lock: &Path,
    js_files: &[PathBuf],
    rust_files: &[PathBuf],
    v8_archive: &Path,
    snapshot_kind: &str,
    product_profile: &str,
    target_arch: &str,
) -> Result<(), String> {
    let manifest_bytes = fs::read(manifest_path)
        .map_err(|error| format!("manifest {} unavailable: {error}", manifest_path.display()))?;
    let manifest: Value = serde_json::from_slice(&manifest_bytes)
        .map_err(|error| format!("manifest JSON is invalid: {error}"))?;

    let snapshot_size = fs::metadata(snapshot_path)
        .map_err(|error| format!("snapshot {} unavailable: {error}", snapshot_path.display()))?
        .len();
    require_materialized_size("snapshot", snapshot_size)?;
    let expected_features = snapshot_profile_features(product_profile)?;
    let expected_feature_hash = snapshot_feature_hash(expected_features);
    let expected_runtime_hash = snapshot_runtime_hash(repo_root, rust_files)?;
    let expected_js_hash = snapshot_js_hash(repo_root, js_files)?;
    let expected_deno = deno_core_version(cargo_lock)?;
    let v8_size = fs::metadata(v8_archive)
        .map_err(|error| format!("V8 archive {} unavailable: {error}", v8_archive.display()))?
        .len();
    require_materialized_size(&format!("V8 archive {}", v8_archive.display()), v8_size)?;
    let expected_v8_hash = sha256_file(v8_archive)
        .map_err(|error| format!("cannot hash V8 archive {}: {error}", v8_archive.display()))?;
    validate_snapshot_identity(
        ManifestIdentity {
            schema_version: manifest.get("schema_version").and_then(Value::as_u64),
            snapshot_kind: manifest.get("snapshot_kind").and_then(Value::as_str),
            profile: manifest.get("profile").and_then(Value::as_str),
            arch: manifest.get("arch").and_then(Value::as_str),
            features_sha256: manifest.get("features_sha256").and_then(Value::as_str),
            rust_sources_sha256: manifest.get("rust_sources_sha256").and_then(Value::as_str),
            v8_archive_sha256: manifest.get("v8_archive_sha256").and_then(Value::as_str),
            js_sources_sha256: manifest.get("js_sources_sha256").and_then(Value::as_str),
            deno_core_version: manifest.get("deno_core_version").and_then(Value::as_str),
            snapshot_size: manifest.get("snapshot_size").and_then(Value::as_u64),
        },
        SnapshotIdentity {
            schema_version: SNAPSHOT_SCHEMA_VERSION,
            snapshot_kind,
            profile: product_profile,
            arch: target_arch,
            features_sha256: &expected_feature_hash,
            rust_sources_sha256: &expected_runtime_hash,
            v8_archive_sha256: &expected_v8_hash,
            js_sources_sha256: &expected_js_hash,
            deno_core_version: &expected_deno,
            snapshot_size,
        },
    )?;

    let manifest_features = manifest
        .get("features")
        .and_then(Value::as_array)
        .ok_or_else(|| "manifest field \"features\" is missing or not an array".to_string())?
        .iter()
        .map(|value| {
            value
                .as_str()
                .ok_or_else(|| "manifest features contains a non-string".to_string())
        })
        .collect::<Result<Vec<_>, _>>()?;
    if manifest_features != expected_features {
        return Err(format!(
            "manifest features mismatch (manifest={manifest_features:?}, target={expected_features:?})"
        ));
    }

    let expected_snapshot_hash = manifest_string(&manifest, "snapshot_sha256")?;
    let actual_snapshot_hash =
        sha256_file(snapshot_path).map_err(|error| format!("cannot hash snapshot: {error}"))?;
    require_equal_hash(
        "snapshot bytes",
        expected_snapshot_hash,
        &actual_snapshot_hash,
    )?;

    Ok(())
}

fn selected_product_profile() -> Result<&'static str, String> {
    let full = std::env::var_os("CARGO_FEATURE_PROFILE_FULL").is_some();
    let slim = std::env::var_os("CARGO_FEATURE_PROFILE_SLIM").is_some();
    match (full, slim) {
        (true, false) => Ok("full"),
        (false, true) => Ok("slim"),
        (true, true) => Err("both snapshot product profiles are enabled".to_string()),
        (false, false) => Err("no named snapshot product profile is enabled".to_string()),
    }
}

fn manifest_string<'a>(manifest: &'a Value, field: &str) -> Result<&'a str, String> {
    manifest
        .get(field)
        .and_then(Value::as_str)
        .ok_or_else(|| format!("manifest field {field:?} is missing or not a string"))
}

fn require_equal_hash(kind: &str, expected: &str, actual: &str) -> Result<(), String> {
    if expected == actual {
        Ok(())
    } else {
        Err(format!(
            "{kind} changed (manifest={}..., current={}...)",
            &expected[..expected.len().min(12)],
            &actual[..actual.len().min(12)],
        ))
    }
}

fn deno_core_version(cargo_lock: &Path) -> Result<String, String> {
    let lock = fs::read_to_string(cargo_lock)
        .map_err(|error| format!("cannot read {}: {error}", cargo_lock.display()))?;
    let mut deno_package = false;
    for line in lock.lines() {
        let line = line.trim();
        if line == "[[package]]" {
            deno_package = false;
        } else if line == "name = \"deno_core\"" {
            deno_package = true;
        } else if deno_package && line.starts_with("version = \"") {
            return line
                .strip_prefix("version = \"")
                .and_then(|value| value.strip_suffix('"'))
                .map(str::to_owned)
                .ok_or_else(|| "malformed deno_core version in Cargo.lock".to_string());
        }
    }
    Err("deno_core package missing from Cargo.lock".to_string())
}
