#!/usr/bin/env bash
# Shared, environment-independent tail of the Windows SDK build: generating the
# export allowlist, staging the prefix, writing the CMake package, and writing
# the package manifest. Sourced by both scripts/build-windows-sdk.sh (WSL, links
# via a synced Windows worktree) and scripts/build-windows-sdk-native.sh (runs
# directly on Windows, e.g. GitHub's windows-latest CI runner).
#
# What is deliberately NOT here: compiling the capi staticlib and linking
# migo.dll. Those two steps differ by environment -- WSL crosses into a Windows
# worktree via wslpath/cmd.exe batch files, native just runs cargo/link.exe in
# place -- which is the whole reason two driver scripts exist instead of one
# branching on "am I in WSL". This file holds only the logic that produces
# identical output regardless of which one called it.
#
# This file is sourced, not executed: no `set -euo pipefail` here (each caller
# sets its own), and no side effects that run merely because a script sourced it.

MIGO_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/python-cmd.sh
source "$MIGO_LIB_DIR/python-cmd.sh"

info() { echo -e "\033[0;36m[win-sdk] $*\033[0m"; }

# Generates the .def export allowlist from include/migo/*.h and writes it to
# out_file. The public surface is exactly the documented migo_* entry points --
# generated from the headers so it cannot drift from them the way a hand-kept
# list would.
windows_sdk_generate_def() {
    local header_dir="$1" out_file="$2"
    {
        echo "EXPORTS"
        "$(python_cmd)" "$MIGO_LIB_DIR/../c-abi-entry-points.py" embedded "$header_dir" \
            | sed 's/^/    /'
    } > "$out_file"
    local def_count=$(( $(wc -l < "$out_file") - 1 ))
    info "generated export allowlist: $def_count migo_* symbols"
    [[ "$def_count" -ge 20 ]] || {
        echo "[win-sdk] suspiciously few exports ($def_count); headers not found?" >&2
        return 1
    }
}

# Stages the package prefix: headers, the linked migo.lib/migo.dll, and the
# runtime DLLs (rusty_v8 + ANGLE) a consumer's process loads by name.
#
# libEGL.dll/libGLESv2.dll are required, not best-effort: a package with no EGL
# is not discoverable as broken until a consumer's process fails to create a
# surface on a machine this build cannot see. d3dcompiler_47.dll is genuinely
# optional depending on how the linked ANGLE was built, so its presence is
# recorded in the manifest (windows_sdk_write_manifest) rather than assumed
# either way -- but test-windows-sdk-contract.sh --strict requires all three,
# so copying leniently here would only move the failure later while leaving a
# package with no EGL on disk in between.
windows_sdk_stage_package() {
    local prefix="$1" include_src="$2" migo_lib_src="$3" migo_dll_src="$4" \
          rusty_v8_dll_src="$5" angle_dir="$6"

    info "staging package at $prefix"
    rm -rf "$prefix"
    mkdir -p "$prefix/include" "$prefix/lib" "$prefix/bin" "$prefix/lib/cmake/migo" "$prefix/share/migo"
    cp -r "$include_src" "$prefix/include/"
    cp "$migo_lib_src" "$prefix/lib/migo.lib"
    cp "$migo_dll_src" "$prefix/bin/migo.dll"
    cp "$rusty_v8_dll_src" "$prefix/bin/rusty_v8.dll"
    local d
    for d in libEGL.dll libGLESv2.dll d3dcompiler_47.dll; do
        [[ -f "$angle_dir/$d" ]] || {
            echo "[win-sdk] required ANGLE runtime missing: $angle_dir/$d" >&2
            echo "[win-sdk] fetch the pinned set with: bash scripts/fetch-windows-angle.sh" >&2
            return 1
        }
        cp "$angle_dir/$d" "$prefix/bin/$d"
    done

    info "staged:"
    find "$prefix" -type f | sed "s|$prefix|  <prefix>|" | sort
}

# Writes the CMake find_package(migo) tree. A SHARED IMPORTED target: the
# consumer links the import lib (migo.lib) and the DLL ships in bin/.
#
# The constraint that put a literal version here is real and is kept:
# windows-sdk-0.1.0 shipped before the C ABI had a Windows platform layer, and
# a released version names a fixed set of bytes -- so those bytes must never
# ship under a version a consumer may already hold. release/VERSION is the
# single forward-moving source; the caller passes it in rather than this
# function deriving it, so this file has no opinion on how a version is read.
windows_sdk_write_cmake_package() {
    local prefix="$1" version="$2"
    cat > "$prefix/lib/cmake/migo/migo-config.cmake" <<'CMAKE'
# Generated by scripts/lib/windows-sdk-package.sh -- do not edit.
#
# Consume with the MSVC toolchain:
#   cmake -S <your_app> -B <build> -DCMAKE_PREFIX_PATH=<this package prefix>
#   find_package(migo REQUIRED)
#   target_link_libraries(app PRIVATE migo::migo)
# The DLLs in <prefix>/bin (migo.dll, rusty_v8.dll, ANGLE) must be on PATH at
# runtime, or copied next to the executable.
cmake_minimum_required(VERSION 3.16)

get_filename_component(MIGO_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

set(MIGO_VERSION "@MIGO_SDK_VERSION@")
set(MIGO_INCLUDE_DIRS "${MIGO_PREFIX}/include")
set(MIGO_IMPLIB "${MIGO_PREFIX}/lib/migo.lib")
set(MIGO_DLL "${MIGO_PREFIX}/bin/migo.dll")

add_library(migo::migo SHARED IMPORTED)
set_target_properties(migo::migo PROPERTIES
    IMPORTED_IMPLIB "${MIGO_IMPLIB}"
    IMPORTED_LOCATION "${MIGO_DLL}"
    INTERFACE_INCLUDE_DIRECTORIES "${MIGO_INCLUDE_DIRS}"
    INTERFACE_COMPILE_DEFINITIONS "MIGO_USE_SHARED"
    INTERFACE_COMPILE_FEATURES "c_std_11")

set(migo_FOUND TRUE)
CMAKE
    sed -i "s|@MIGO_SDK_VERSION@|$version|" "$prefix/lib/cmake/migo/migo-config.cmake"

    cat > "$prefix/lib/cmake/migo/migo-config-version.cmake" <<CMAKE
# Generated by scripts/lib/windows-sdk-package.sh -- do not edit.
set(PACKAGE_VERSION "$version")
if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if(PACKAGE_VERSION VERSION_EQUAL PACKAGE_FIND_VERSION)
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
endif()
CMAKE
}

# Writes share/migo/windows-<arch>-manifest.json. The runtime_dependencies
# list is the part with teeth: a Windows consumer must redistribute these
# DLLs, and the process loads them by name, so the package has to say which
# ones it shipped -- turning "the ANGLE directory was incomplete" from a
# silent shipping defect into a failure windows_sdk_stage_package already
# raises before this function is ever reached.
#
# arch is migo's internal word (x86_64 / aarch64, matching target.arch
# elsewhere in this repo's manifests); target is the full Rust triple. Kept as
# two separate parameters rather than derived from one another because the
# aarch64 -> arm64 word substitution is a *public*-facing convention (see
# build-ohos-sdk.sh's public_ohos_arch() and build-v8-windows.sh's own
# comment on the same convention) that belongs at the call site, not
# hardcoded into this shared file.
windows_sdk_write_manifest() {
    local prefix="$1" version="$2" arch="${3:-x86_64}" target="${4:-x86_64-pc-windows-msvc}"
    local sha_of
    sha_of() { sha256sum "$1" | cut -d' ' -f1; }

    # Same four names test-windows-sdk-contract.sh requires, kept in one order
    # so the manifest and the gate cannot disagree about what a consumer must ship.
    local all_runtime=(migo.dll rusty_v8.dll libEGL.dll libGLESv2.dll d3dcompiler_47.dll)

    local runtime_json first=1 d
    runtime_json=""
    for d in "${all_runtime[@]}"; do
        (( first )) || runtime_json+=","
        first=0
        runtime_json+=$'\n      {"file": "bin/'"$d"'", "sha256": "'"$(sha_of "$prefix/bin/$d")"'"}'
    done
    runtime_json="[${runtime_json}"$'\n    ]'

    local manifest_path="$prefix/share/migo/windows-$arch-manifest.json"
    cat > "$manifest_path" <<MANIFEST
{
  "schema": "migo-windows-package-manifest/v1",
  "version": "$version",
  "product_profile": "full",
  "build_type": "release",
  "target": "$target",
  "os": "windows",
  "abi": "msvc",
  "arch": "$arch",
  "snapshot_policy": "none",
  "abi_note": "migo.dll is linked from the capi staticlib with an explicit .def export allowlist, so the export table is exactly the documented migo_* surface. V8 links against its own libc++ and therefore ships as a separate rusty_v8.dll rather than being absorbed into migo.dll.",
  "runtime_dependencies": $runtime_json,
  "artifacts": {
    "lib/migo.lib": "$(sha_of "$prefix/lib/migo.lib")",
    "bin/migo.dll": "$(sha_of "$prefix/bin/migo.dll")"
  },
  "known_gaps": [
    "v8 startup snapshot: not embedded for this platform yet (runtime-v8/build.rs embeds for android and linux, not windows -- no SNAPSHOT-full-windows-$arch.bin has been generated), so a cold start parses extension JS from source instead of deserialising a V8 heap",
    "NuGet packaging is not implemented; the package is a CMake find_package tree"
  ]
}
MANIFEST

    "$(python_cmd)" -m json.tool "$manifest_path" >/dev/null \
        || { echo "[win-sdk] the generated manifest is not valid JSON" >&2; return 1; }
}
