#!/usr/bin/env python3
"""Stage the engine's JavaScript API layer for the Performance+ producer.

On iOS Performance+ content runs in a Worker inside WebKit's WebContent process,
and so must the engine's JavaScript -- WebGL, Canvas2D, `migo.*` -- because it is
the layer content calls. That JavaScript is written for deno_core: it imports
`ext:core/ops`, `ext:core/mod.js` and `ext:<extension>/<file>`. This writes it out
as plain ES modules a Worker can import, without changing a line of it:

  engine/<extension>/<file>.js  the engine's modules, with only their import
                                specifiers rewritten to relative paths
  engine/core/ops.mjs           one export per op the engine imports: the
                                implementation from `lane-<lane>.mjs` when the
                                producer has one, otherwise a function that throws
                                a stable error naming the op and its lane
  engine/core/mod.mjs           `primordials` (the names the engine uses) and
                                `core`, from `engine-core.mjs`
  engine/boot.mjs               evaluates the modules in deno_core's order
  engine/manifest.json          what was staged and how many ops are implemented

Everything that decides the output is derived: the module graph and evaluation
order from the extension registrations (scripts/lib/runtime_modules.py), the ops
and their lanes from contracts/runtime/op-boundary.json. A lane module that
implements an op on a lane the contract does not give it, an import the bundle
cannot satisfy, or a primordials name nothing can produce stops the build.

usage: gen-performance-plus-engine.py [--root REPO] --out DIR [--with-producer]

--with-producer also copies platforms/apple/WebContent/PerformancePlus/src into
DIR, so DIR is a complete resource root -- what tests load. The SDK build copies
the producer itself and runs this into the same directory.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import shutil
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent / "lib"))
import runtime_modules  # noqa: E402
import runtime_ops  # noqa: E402

PRODUCER_SRC = pathlib.Path("platforms/apple/WebContent/PerformancePlus/src")
CONTRACT = pathlib.Path("contracts/runtime/op-boundary.json")
SERVICE_OPS_CONTRACT = pathlib.Path("contracts/runtime/service-ops.json")
SERVICE_OPS_MODULE = PRODUCER_SRC / "service-ops.mjs"
SERVICE_OP_ENTRY = re.compile(r"^\s*(op_[A-Za-z0-9_]+):\s*(\d+),\s*$", re.M)
HOST_EVENTS_CONTRACT = pathlib.Path("contracts/runtime/host-events.json")
HOST_EVENTS_MODULE = PRODUCER_SRC / "host-events.mjs"
HOST_EVENT_ENTRY = re.compile(r"^\s*(_internal[A-Za-z0-9_]+):\s*(\d+),\s*$", re.M)
PROFILE = "performance_plus"
GENERATED = "// @generated by scripts/gen-performance-plus-engine.py -- do not edit.\n"

LANE_EXPORT = re.compile(r"(?m)^export\s+(?:async\s+)?(?:function\s+|const\s+|let\s+)(op_[A-Za-z0-9_]+)\b")
PRIMORDIAL_DESTRUCTURE = re.compile(r"(?:const|let|var)\s*\{([^}]*)\}\s*=\s*primordials\b")
OPS_IMPORT = re.compile(r"import\s*\{(?P<names>[^}]*)\}\s*from\s*[\"']ext:core/ops[\"']", re.S)
CORE_IMPORT = re.compile(r"import\s*\{(?P<names>[^}]*)\}\s*from\s*[\"']ext:core/mod\.js[\"']", re.S)
# What `engine/core/mod.mjs` can provide. `internals` is deno's object modules
# attach private hooks to; the engine imports it and attaches nothing, so it is
# an empty, extensible object -- a name the engine asks for that is not listed
# here stops the build instead.
CORE_EXPORTS = ("core", "internals", "primordials")
CORE_MEMBER = re.compile(r"\bcore\.([A-Za-z_][A-Za-z0-9_]*)")
CORE_DESTRUCTURE = re.compile(r"(?:const|let|var)\s*\{([^}]*)\}\s*=\s*core\b")


class BuildError(Exception):
    pass


OP_ARGS_MODULE = PRODUCER_SRC / "op-args.mjs"
# `/** ... @kind a, b ... */ export function name(` in op-args.mjs.
CONVERTER_KINDS = re.compile(
    r"/\*\*(?:(?!\*/).)*?@kind\s+([a-z0-9_, ]+?)\s*\n(?:(?!\*/).)*?\*/\s*export\s+function\s+(\w+)",
    re.S,
)
# Kinds deno_core hands the body without a fixed conversion to restate.
NO_CONVERSION_RULE = {"serde", "v8_value", "option_v8_value"}
TOP_FUNCTION = re.compile(r"(?m)^(?:export\s+)?(?:async\s+)?function\s+(\w+)\s*\(")
TOP_ARROW = re.compile(r"(?m)^(?:export\s+)?const\s+(\w+)\s*=\s*(?:async\s*)?\(")
TOP_FACTORY_USE = re.compile(r"(?m)^export\s+const\s+(op_\w+)\s*=\s*(\w+)\s*\(")


def mask_js(text: str) -> str:
    """The source with comments and the contents of string and template literals
    blanked, length preserved -- enough structure to find a function's braces.
    The lane modules contain no regular-expression literals; a lane that adds
    one needs this taught about them first."""
    out = list(text)
    length, index = len(text), 0

    def blank(start: int, stop: int) -> None:
        for position in range(start, min(stop, length)):
            if out[position] != "\n":
                out[position] = " "

    while index < length:
        if text.startswith("//", index):
            stop = text.find("\n", index)
            stop = length if stop < 0 else stop
            blank(index, stop)
            index = stop
        elif text.startswith("/*", index):
            stop = text.find("*/", index + 2)
            stop = length if stop < 0 else stop + 2
            blank(index, stop)
            index = stop
        elif text[index] in "\"'`":
            quote, cursor = text[index], index + 1
            while cursor < length and text[cursor] != quote:
                cursor += 2 if text[cursor] == "\\" else 1
            blank(index + 1, cursor)
            index = cursor + 1
        else:
            index += 1
    return "".join(out)


def function_spans(masked: str) -> dict[str, tuple[int, int]]:
    """Top-level functions -- declarations and `const f = (...) => ...` -- by
    name, as the span of their parameters and body."""
    spans: dict[str, tuple[int, int]] = {}
    for pattern in (TOP_FUNCTION, TOP_ARROW):
        for match in pattern.finditer(masked):
            paren = match.end() - 1
            params = runtime_ops.balanced(masked, paren)
            cursor = paren + len(params) + 2
            arrow = re.match(r"\s*=>\s*", masked[cursor:])
            if arrow:
                cursor += arrow.end()
                inner = re.match(r"(?:async\s+)?function\s*\w*\s*\(", masked[cursor:])
                if inner:
                    open_paren = cursor + inner.end() - 1
                    cursor = open_paren + len(runtime_ops.balanced(masked, open_paren)) + 2
            brace = masked.find("{", cursor)
            if brace < 0 or masked[cursor:brace].strip():
                # An expression body: up to the end of the statement.
                stop = masked.find(";", cursor)
                spans[match.group(1)] = (match.start(), stop if stop > 0 else len(masked))
                continue
            body = runtime_ops.balanced(masked, brace)
            spans[match.group(1)] = (match.start(), brace + len(body) + 2)
    return spans


def converter_kinds(root: pathlib.Path) -> dict[str, set[str]]:
    text = (root / OP_ARGS_MODULE).read_text(encoding="utf-8")
    kinds = {name: {kind.strip() for kind in listed.split(",") if kind.strip()}
             for listed, name in CONVERTER_KINDS.findall(text)}
    if not kinds:
        raise BuildError(f"{OP_ARGS_MODULE} declares no @kind converters")
    return kinds


def check_conversions(root: pathlib.Path, implemented: dict[str, str]) -> int:
    """Every argument a lane converts is one the op takes, converted by the rule
    deno_core applies to it.

    A lane converts each argument by calling one of op-args.mjs's functions with
    the Rust parameter's name: `smiU32(canvasId, "canvas_id")`. The op's Rust
    signature says which conversion deno_core applies to `canvas_id`
    (runtime_ops.param_kind), and op-args.mjs says which kinds each function
    implements (`@kind`, pinned to V8 by the op-argument agreement gate). So a
    lane that converts a `#[smi] u32` with the plain-`u32` rule, or names a
    parameter the op does not have, stops the build -- the mismatch is a value
    that differs between the two runtimes for the same call.

    Every argument is converted, even one the lane does not otherwise use:
    deno_core converts before the body runs, so a value it refuses is a
    TypeError in the embedded runtime whatever the body would have done with
    it. The exceptions are the kinds with no single rule to restate --
    `#[serde]` and a raw `v8::Local` -- which the lane handles as its op's
    comment says.

    Conversions in a helper are checked for every op that reaches the helper;
    one no op reaches is an error, because nothing then checks it.
    """
    kinds = converter_kinds(root)
    call = re.compile(
        r"\b(" + "|".join(sorted(kinds, key=len, reverse=True)) + r")\s*\("
        r"(?:[^()]|\([^()]*\))*?,\s*\"([A-Za-z0-9_]+)\"\s*\)"
    )
    ops, _ = runtime_ops.surface(root)
    checked = 0
    problems: list[str] = []
    for path in sorted((root / PRODUCER_SRC).glob("lane-*.mjs")):
        text = path.read_text(encoding="utf-8")
        masked = mask_js(text)
        spans = function_spans(masked)
        conversions = {
            name: [(m.group(1), m.group(2)) for m in call.finditer(text, start, stop)]
            for name, (start, stop) in spans.items()
        }
        mentions = {
            name: set(re.findall(r"\b[A-Za-z_]\w*\b", masked[start:stop])) - {name}
            for name, (start, stop) in spans.items()
        }
        factories = dict(TOP_FACTORY_USE.findall(masked))
        reached: set[str] = set()

        def closure(first: str) -> list[str]:
            seen, stack = [], [first]
            while stack:
                current = stack.pop()
                if current in seen or current not in spans:
                    continue
                seen.append(current)
                stack.extend(sorted(n for n in mentions[current]
                                    if n in spans and not n.startswith("op_")))
            return seen

        for op in sorted(name for name, module in implemented.items() if module == path.name):
            root_function = op if op in spans else factories.get(op)
            if root_function is None:
                problems.append(f"{path.name}: {op} is neither a function nor made by one")
                continue
            params = ops[op].params if op in ops else None
            functions = closure(root_function)
            reached.update(functions)
            found = [conversion for function in functions for conversion in conversions[function]]
            if params is None:
                if found:
                    problems.append(f"{path.name}: {op}'s signature is macro-stamped, so its conversions cannot be checked")
                continue
            by_name = dict(params)
            converted = {param for _, param in found}
            for param, kind in params:
                if param not in converted and kind not in NO_CONVERSION_RULE:
                    problems.append(
                        f"{path.name}: {op} leaves `{param}` ({kind}) unconverted; deno_core converts every "
                        f"argument an op takes, and one that is not converted here is a value the two runtimes "
                        f"can disagree on")
            for converter, param in found:
                checked += 1
                if param not in by_name:
                    problems.append(
                        f"{path.name}: {op} converts `{param}`, which its Rust signature does not take "
                        f"(it takes {', '.join(by_name) or 'nothing'})")
                elif by_name[param] not in kinds[converter]:
                    fitting = sorted(name for name, listed in kinds.items() if by_name[param] in listed)
                    problems.append(
                        f"{path.name}: {op} converts `{param}` ({by_name[param]}) with {converter}; "
                        f"deno_core converts it as {' or '.join(fitting) or 'no function op-args.mjs has'}")
        for name, found in conversions.items():
            if found and name not in reached:
                problems.append(f"{path.name}: {name} converts arguments but no op reaches it, so nothing checks them")
    if problems:
        raise BuildError("argument conversions disagree with the ops' Rust signatures:\n  " + "\n  ".join(problems))
    return checked


def relative_specifier(target: str, importer: str) -> str:
    """The path from `engine/<importer extension>/` to what `target` names."""
    if target == "ext:core/ops":
        return "../core/ops.mjs"
    if target == "ext:core/mod.js":
        return "../core/mod.mjs"
    if target.startswith("ext:"):
        extension, _, file = target[len("ext:") :].partition("/")
        importer_extension = importer[len("ext:") :].split("/", 1)[0]
        return f"./{file}" if extension == importer_extension else f"../{extension}/{file}"
    return target


def rewrite(source: str, importer: str) -> str:
    out: list[str] = []
    cursor = 0
    for match in runtime_modules.STATIC_IMPORT.finditer(source):
        group = "spec" if match.group("spec") is not None else "bare"
        start, end = match.span(group)
        out.append(source[cursor:start])
        out.append(relative_specifier(match.group(group), importer))
        cursor = end
    out.append(source[cursor:])
    rewritten = "".join(out)
    if "ext:" in runtime_ops.strip_js_comments(rewritten):
        leftover = re.search(r"[\"']ext:[^\"']*[\"']", runtime_ops.strip_js_comments(rewritten))
        if leftover:
            raise BuildError(f"{importer} still names {leftover.group(0)} after rewriting its imports")
    return rewritten


def lane_implementations(root: pathlib.Path, lanes: dict[str, str]) -> dict[str, str]:
    """op -> the lane module that implements it, checked against the contract."""
    implemented: dict[str, str] = {}
    for path in sorted((root / PRODUCER_SRC).glob("lane-*.mjs")):
        lane = path.stem[len("lane-") :]
        if lane not in ("local", "stream", "command", "sync", "async"):
            raise BuildError(f"{path.name} names no lane that has implementations")
        for name in LANE_EXPORT.findall(path.read_text(encoding="utf-8")):
            if name not in lanes:
                raise BuildError(f"{path.name} exports {name}, which the contract does not classify")
            if lanes[name] != lane:
                raise BuildError(f"{path.name} implements {name}, whose lane is {lanes[name]}")
            if name in implemented:
                raise BuildError(f"{name} is implemented by both {implemented[name]} and {path.name}")
            implemented[name] = path.name
    return implemented


def check_service_ops(root: pathlib.Path, lanes: dict[str, str]) -> dict[str, int]:
    """The producer's op-number table against the contract, entry for entry.

    A number that differs is a producer calling one op and the host running
    another with the right-looking arguments, so drift stops the build rather
    than shipping. Every numbered op must also be one the boundary contract
    sends to the host: async, command or sync.
    """
    contract = json.loads((root / SERVICE_OPS_CONTRACT).read_text(encoding="utf-8"))["ops"]
    declared = {name: int(number) for name, number in SERVICE_OP_ENTRY.findall(
        (root / SERVICE_OPS_MODULE).read_text(encoding="utf-8"))}
    if declared != contract:
        missing = sorted(set(contract) - set(declared))
        extra = sorted(set(declared) - set(contract))
        different = sorted(n for n in set(contract) & set(declared) if contract[n] != declared[n])
        raise BuildError(
            f"{SERVICE_OPS_MODULE} disagrees with {SERVICE_OPS_CONTRACT}: "
            f"missing {missing}, extra {extra}, renumbered {different}"
        )
    numbers = list(contract.values())
    if len(set(numbers)) != len(numbers) or 0 in numbers:
        raise BuildError(f"{SERVICE_OPS_CONTRACT} reuses a number or uses zero")
    for name in contract:
        if lanes.get(name) not in ("async", "command", "sync"):
            raise BuildError(f"{name} has a service number but its lane is {lanes.get(name)}")
    return contract


def check_host_events(root: pathlib.Path) -> dict[str, int]:
    """The producer's host-event table against the contract, entry for entry:
    a number that differs is the host sending a touch and the producer calling
    the keyboard's hook with its arguments."""
    contract = json.loads((root / HOST_EVENTS_CONTRACT).read_text(encoding="utf-8"))["events"]
    declared = {name: int(number) for name, number in HOST_EVENT_ENTRY.findall(
        (root / HOST_EVENTS_MODULE).read_text(encoding="utf-8"))}
    if declared != contract:
        missing = sorted(set(contract) - set(declared))
        extra = sorted(set(declared) - set(contract))
        different = sorted(n for n in set(contract) & set(declared) if contract[n] != declared[n])
        raise BuildError(
            f"{HOST_EVENTS_MODULE} disagrees with {HOST_EVENTS_CONTRACT}: "
            f"missing {missing}, extra {extra}, renumbered {different}"
        )
    numbers = list(contract.values())
    if len(set(numbers)) != len(numbers) or 0 in numbers:
        raise BuildError(f"{HOST_EVENTS_CONTRACT} reuses a number or uses zero")
    return contract


def build(root: pathlib.Path, out: pathlib.Path, with_producer: bool) -> dict:
    contract = json.loads((root / CONTRACT).read_text(encoding="utf-8"))
    lanes: dict[str, str] = {}
    extension_of: dict[str, str] = {}
    for extension, entry in contract["extensions"].items():
        for name, value in entry["ops"].items():
            lanes[name] = value if isinstance(value, str) else value["lane"]
            extension_of[name] = extension

    entries, reachable, modules, _ = runtime_modules.graph(root)
    implemented = lane_implementations(root, lanes)
    service_ops = check_service_ops(root, lanes)
    host_events = check_host_events(root)
    conversions = check_conversions(root, implemented)

    if with_producer:
        if out.exists():
            shutil.rmtree(out)
        shutil.copytree(root / PRODUCER_SRC, out)
    engine = out / "engine"
    if engine.exists():
        shutil.rmtree(engine)
    (engine / "core").mkdir(parents=True)

    primordials: set[str] = set()
    core_members: set[str] = set()
    ops_needed: set[str] = set()
    for specifier in reachable:
        source = modules[specifier].read_text(encoding="utf-8")
        if not source.isascii():
            raise BuildError(f"{specifier} is not ASCII; the engine's embedded JavaScript must be")
        stripped = runtime_ops.strip_js_comments(source)
        for match in PRIMORDIAL_DESTRUCTURE.finditer(stripped):
            for item in match.group(1).split(","):
                name = item.split(":")[0].strip()
                if name:
                    primordials.add(name)
        core_members.update(CORE_MEMBER.findall(stripped))
        for match in CORE_DESTRUCTURE.finditer(stripped):
            core_members.update(item.split(":")[0].strip() for item in match.group(1).split(",") if item.strip())
        for match in CORE_IMPORT.finditer(stripped):
            for item in match.group("names").split(","):
                name = item.split(" as ")[0].strip()
                if name and name not in CORE_EXPORTS:
                    raise BuildError(f"{specifier} imports {name} from ext:core/mod.js, which this producer does not provide")
        for match in OPS_IMPORT.finditer(stripped):
            ops_needed.update(item.split(" as ")[0].strip() for item in match.group("names").split(",") if item.strip())
        ops_needed.update(runtime_ops.CORE_OPS_REF.findall(stripped))
        extension, _, file = specifier[len("ext:") :].partition("/")
        target = engine / extension / file
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rewrite(source, specifier), encoding="utf-8")

    unclassified = sorted(ops_needed - set(lanes))
    if unclassified:
        raise BuildError(f"the staged modules import ops the contract does not classify: {unclassified}")

    ops_lines = [GENERATED, 'import { notImplemented, notSupported } from "../../engine-core.mjs";\n']
    by_module: dict[str, list[str]] = {}
    for name in sorted(lanes):
        if name in implemented:
            by_module.setdefault(implemented[name], []).append(name)
    for module_name, names in sorted(by_module.items()):
        ops_lines.append(f'export {{ {", ".join(names)} }} from "../../{module_name}";\n')
    for name in sorted(lanes):
        if name in implemented:
            continue
        if lanes[name] == "unsupported":
            ops_lines.append(
                f'export const {name} = notSupported("{name}", "{extension_of[name]}", "{PROFILE}");\n'
            )
        else:
            ops_lines.append(f'export const {name} = notImplemented("{name}", "{lanes[name]}");\n')
    (engine / "core" / "ops.mjs").write_text("".join(ops_lines), encoding="utf-8")

    (engine / "core" / "mod.mjs").write_text(
        GENERATED
        + 'import * as ops from "./ops.mjs";\n'
        + 'import { makeCore, makePrimordials } from "../../engine-core.mjs";\n'
        + f"export const primordials = makePrimordials({json.dumps(sorted(primordials))});\n"
        + "export const core = makeCore(ops);\n"
        + "export const internals = { __proto__: null };\n",
        encoding="utf-8",
    )

    boot = [GENERATED, "// The engine's modules, evaluated in the order deno_core evaluates them.\n"]
    for entry in entries:
        extension, _, file = entry[len("ext:") :].partition("/")
        boot.append(f'import "./{extension}/{file}";\n')
    (engine / "boot.mjs").write_text("".join(boot), encoding="utf-8")

    counts: dict[str, dict[str, int]] = {}
    for name, lane in lanes.items():
        entry = counts.setdefault(lane, {"classified": 0, "implemented": 0})
        entry["classified"] += 1
        if name in implemented or lane == "unsupported":
            entry["implemented"] += 1
    manifest = {
        "schema_version": 1,
        "profile": PROFILE,
        "entries": entries,
        "modules": len(reachable),
        "primordials": len(primordials),
        # Checked against what `engine-core.mjs` provides by the producer's
        # engine test, which is the one place that can run it.
        "core_members": sorted(core_members),
        "ops": dict(sorted(counts.items())),
        "implemented": sorted(implemented),
        "service_ops": len(service_ops),
        "host_events": len(host_events),
        "conversions_checked": conversions,
    }
    (engine / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", default=".", type=pathlib.Path)
    parser.add_argument("--out", required=True, type=pathlib.Path)
    parser.add_argument("--with-producer", action="store_true")
    args = parser.parse_args(argv)
    try:
        manifest = build(args.root.resolve(), args.out.resolve(), args.with_producer)
    except (BuildError, ValueError) as error:
        print(f"gen-performance-plus-engine: {error}", file=sys.stderr)
        return 1
    implemented = sum(entry["implemented"] for entry in manifest["ops"].values())
    total = sum(entry["classified"] for entry in manifest["ops"].values())
    print(
        f"staged {manifest['modules']} engine modules, {manifest['primordials']} primordials, "
        f"{implemented}/{total} ops answered on this producer (unsupported counts as answered)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
