// The numbers service ops travel under on the service stream.
//
// contracts/runtime/service-ops.json is the source. This copy is checked
// against it entry for entry when the engine is staged
// (scripts/gen-performance-plus-engine.py), and the host's copy by a Rust test,
// so the three cannot disagree without a build failing. Append only.

export const SERVICE_OP = Object.freeze({
  op_storage_get: 1,
  op_storage_set: 2,
  op_storage_remove: 3,
  op_storage_clear: 4,
  op_storage_info: 5,
  op_storage_get_async: 6,
  op_storage_set_async: 7,
  op_storage_remove_async: 8,
  op_storage_clear_async: 9,
  op_storage_info_async: 10,
  op_create_buffer_url: 11,
  op_revoke_buffer_url: 12,
  op_load_image: 13,
  op_load_image_subrect: 14,
  op_preload_images: 15,
  op_destroy_image: 16,
  op_clear_image_cache: 17,
  op_get_image_cache_stats: 18,
  op_access: 19,
  op_write_or_append_file: 20,
  op_open_file: 21,
  op_close_file: 22,
  op_copy_file: 23,
  op_fstat: 24,
  op_ftruncate: 25,
  op_mkdir: 26,
  op_readdir: 27,
  op_unlink: 28,
  op_rename: 29,
  op_rmdir: 30,
  op_stat: 31,
  op_write_file: 32,
  op_read_file: 33,
  op_read_fd: 34,
  op_read_fd_into: 35,
  op_read_compressed_file: 36,
  op_read_zip_entry: 37,
  op_unzip: 38,
  op_get_file_info: 39,
  op_list_saved_files: 40,
  op_access_sync: 41,
  op_write_or_append_file_sync: 42,
  op_open_file_sync: 43,
  op_close_file_sync: 44,
  op_copy_file_sync: 45,
  op_fstat_sync: 46,
  op_ftruncate_sync: 47,
  op_mkdir_sync: 48,
  op_readdir_sync: 49,
  op_unlink_sync: 50,
  op_rename_sync: 51,
  op_rmdir_sync: 52,
  op_stat_sync: 53,
  op_write_file_sync: 54,
  op_read_file_sync: 55,
  op_read_fd_sync: 56,
  op_read_fd_into_sync: 57,
  op_read_compressed_file_sync: 58,
  op_get_file_info_sync: 59,
  op_require_resolve_and_read: 60,
});
