use parking_lot::{Mutex, RwLock};
use std::collections::HashMap;
use std::sync::Arc;
use std::sync::LazyLock;
use std::sync::atomic::{AtomicU32, Ordering};
use tokio::sync::oneshot;

pub type LoadResult = Result<(ImageCacheKey, u32, (usize, usize)), String>;

/// Independent counter for shared image IDs.
/// Starts from a high range to reduce collision risk with caller image IDs
/// generated by the render thread (which start from 1 and count up).
static NEXT_SHARED_ID: AtomicU32 = AtomicU32::new(0x4000_0000);

/// Allocate a unique shared image ID that is distinct from any caller
/// image ID.  Used as the key in the render thread's `shared_fv_images`.
pub fn alloc_shared_id() -> u32 {
    NEXT_SHARED_ID.fetch_add(1, Ordering::Relaxed)
}

/// Structured cache key: `(canonical_src, mount_generation, target_w, target_h)`.
///
/// **The same type as the decoded-bytes cache's key, not a convertible one.**
/// This table sits directly above `migo_io::image_cache`, and every alias
/// operation crosses that boundary: a bind pins, a release unpins, and a
/// `texSubImage2D(image)` looks the bytes up. While the two sides spoke
/// different key shapes, each crossing had to rebuild the key, which is a heap
/// allocation on a path taken per call. Sharing the type deletes the conversion
/// rather than making it cheaper, and makes an encoding drift between the two
/// sides impossible to write.
///
/// A tuple rather than a concatenated string because `:` is a legal path
/// character on Linux, so concatenation would admit delimiter collision.
pub type ImageCacheKey = migo_io::image_cache::ImageCacheKey;

/// Build a cache key from a resolved path, optional resize dimensions,
/// and mount generation.
///
/// A requested size gets a slot of its own: `createImageBitmap` and
/// `drawImage(…, dw, dh)` ask for pre-resized pixels, and serving them the
/// full-resolution decode would hand back the wrong bitmap. Absent dimensions
/// take the `(…, 0, 0)` full-resolution sentinel that
/// [`migo_io::image_cache::full_res_key`] produces — the op boundary maps a
/// zero-valued request to `None`, so a zero here always means "unresized".
pub fn make_cache_key(
    src: &str,
    target_width: Option<u32>,
    target_height: Option<u32>,
    mount_generation: u64,
) -> ImageCacheKey {
    match (target_width, target_height) {
        (Some(tw), Some(th)) => {
            migo_io::image_cache::resized_key(src.to_string(), mount_generation, tw, th)
        }
        _ => migo_io::image_cache::full_res_key(src.to_string(), mount_generation),
    }
}

pub struct SharedImageEntry {
    pub shared_image_id: u32,
    pub refs: usize,
    pub dims: (usize, usize),
}

pub struct ImageCache {
    // keyed by (canonical src, mount generation, target w, target h)
    by_src: HashMap<ImageCacheKey, SharedImageEntry>,
    // alias (caller image_id) -> shared_image_id
    alias_to_shared: HashMap<u32, u32>,
    // shared_image_id -> cache key
    shared_to_key: HashMap<u32, ImageCacheKey>,

    // in-flight loads: key -> list of waiters
    loading_map: HashMap<ImageCacheKey, Vec<oneshot::Sender<LoadResult>>>,
    // image ids waiting on an in-flight load; used to prevent destroy-before-
    // completion from resurrecting aliases and refcounts.
    pending_alias_to_key: HashMap<u32, ImageCacheKey>,
}

pub enum BeginLoadResult {
    AlreadyLoaded((u32, (usize, usize))),
    Join(oneshot::Receiver<LoadResult>),
    StartLoading,
}

impl ImageCache {
    pub fn new() -> Self {
        Self {
            by_src: HashMap::new(),
            alias_to_shared: HashMap::new(),
            shared_to_key: HashMap::new(),
            loading_map: HashMap::new(),
            pending_alias_to_key: HashMap::new(),
        }
    }

    /// Called at start of op_load_image: remove previous alias and dec refs.
    /// Returns Some(shared_id) if refs dropped to 0 -> caller should destroy that shared_id.
    pub fn remove_previous_alias(&mut self, image_id: u32) -> Option<u32> {
        if let Some(shared_id) = self.alias_to_shared.remove(&image_id) {
            if let Some(key) = self.shared_to_key.get(&shared_id).cloned() {
                if let Some(entry) = self.by_src.get_mut(&key) {
                    entry.refs = entry.refs.saturating_sub(1);
                    // H-5: each alias removal releases exactly one
                    // pin on the io-side LRU entry.  When refs hits
                    // zero the full unpin drops the count back to
                    // regular-LRU eligibility so the bytes can age
                    // out normally; idle entries don't deserve
                    // permanent residence any more than the caller
                    // deserves a silent black texture.
                    migo_io::image_cache::global_cache().unpin(&key);
                    if entry.refs == 0 {
                        self.by_src.remove(&key);
                        self.shared_to_key.remove(&shared_id);
                        return Some(shared_id);
                    }
                }
            }
        }
        self.pending_alias_to_key.remove(&image_id);
        None
    }

    pub fn begin_load(&mut self, image_id: u32, key: &ImageCacheKey) -> BeginLoadResult {
        // already loaded
        if let Some(entry) = self.by_src.get_mut(key) {
            entry.refs = entry.refs.saturating_add(1);
            let shared_id = entry.shared_image_id;

            self.alias_to_shared.insert(image_id, shared_id);
            self.shared_to_key
                .entry(shared_id)
                .or_insert_with(|| key.clone());
            // H-5: every refs++ site must pair with a pin to keep
            // the live-vs-cached split consistent.  The io cache
            // side counts pins additively, so two aliases to the
            // same shared image hold two pins; releasing one
            // decrements without making the entry evictable.
            migo_io::image_cache::global_cache().pin(key);

            return BeginLoadResult::AlreadyLoaded((shared_id, entry.dims));
        }

        // loading in progress
        if self.loading_map.contains_key(key) {
            let (tx, rx) = oneshot::channel();
            self.loading_map.get_mut(key).unwrap().push(tx);
            self.pending_alias_to_key.insert(image_id, key.clone());
            return BeginLoadResult::Join(rx);
        }

        // become loader
        self.loading_map.insert(key.clone(), Vec::new());
        BeginLoadResult::StartLoading
    }

    /// Register the `image_id → shared_id` mapping immediately when a load
    /// starts, before the render thread responds.  This ensures
    /// `try_release_and_get_destroy_rid(image_id)` resolves to the correct
    /// `shared_id` even while the upload is still in flight.
    ///
    /// `finish_load` will overwrite with the same value (idempotent).
    pub fn register_inflight_alias(&mut self, image_id: u32, shared_id: u32) {
        self.alias_to_shared.insert(image_id, shared_id);
    }

    /// Called by *joiners* after they got (shared_id, dims), to ensure alias/ref is correct
    /// even if JS does not replace image_id.
    pub fn bind_alias_existing(
        &mut self,
        image_id: u32,
        requested_key: &ImageCacheKey,
        actual_key: &ImageCacheKey,
        shared_id: u32,
    ) {
        match self.pending_alias_to_key.get(&image_id) {
            Some(pending_key) if pending_key == requested_key => {
                self.pending_alias_to_key.remove(&image_id);
            }
            _ => return,
        }
        if let Some(entry) = self.by_src.get_mut(actual_key) {
            // entry should exist already
            entry.refs = entry.refs.saturating_add(1);
            self.alias_to_shared.insert(image_id, shared_id);
            self.shared_to_key
                .entry(shared_id)
                .or_insert_with(|| actual_key.clone());
            // H-5: joiner became a real alias; pin the io entry
            // to keep bytes alive for its texImage2D path.
            migo_io::image_cache::global_cache().pin(actual_key);
        }
    }

    /// Called by the loader when finished.
    ///
    /// `shared_id` is an independently allocated ID (via [`alloc_shared_id`])
    /// used as the key in the render thread's texture map.  It must NOT be
    /// the same as `loader_image_id` — reusing the caller ID would cause
    /// texture map corruption when the loader alias re-loads a different src
    /// while other aliases still reference the old shared entry.
    pub fn finish_load(
        &mut self,
        loader_image_id: u32,
        shared_id: u32,
        requested_key: &ImageCacheKey,
        actual_key: &ImageCacheKey,
        res: Result<(usize, usize), String>,
    ) -> Option<u32> {
        let Some(waiters) = self.loading_map.remove(requested_key) else {
            return None;
        };

        match res {
            Ok(dims) => {
                let loader_alive =
                    self.alias_to_shared.get(&loader_image_id).copied() == Some(shared_id);
                let pending_refs = self
                    .pending_alias_to_key
                    .values()
                    .filter(|pending| *pending == requested_key)
                    .count();
                if !loader_alive && pending_refs == 0 {
                    return Some(shared_id);
                }

                if let Some(existing) = self.by_src.get_mut(actual_key) {
                    let existing_shared_id = existing.shared_image_id;
                    if loader_alive {
                        existing.refs = existing.refs.saturating_add(1);
                        self.alias_to_shared
                            .insert(loader_image_id, existing_shared_id);
                        // H-5: loader morphed into a real alias.
                        migo_io::image_cache::global_cache().pin(actual_key);
                    }
                    self.shared_to_key
                        .insert(existing_shared_id, actual_key.clone());

                    for tx in waiters {
                        let _ =
                            tx.send(Ok((actual_key.clone(), existing_shared_id, existing.dims)));
                    }

                    return if existing_shared_id == shared_id {
                        None
                    } else {
                        self.shared_to_key.remove(&shared_id);
                        Some(shared_id)
                    };
                }

                self.by_src.insert(
                    actual_key.clone(),
                    SharedImageEntry {
                        shared_image_id: shared_id,
                        refs: usize::from(loader_alive),
                        dims,
                    },
                );
                if loader_alive {
                    self.alias_to_shared.insert(loader_image_id, shared_id);
                    // H-5: new shared-entry path; pin for the
                    // loader's alias.  Joiners (if any) will pin
                    // separately when their `bind_alias_existing`
                    // resolves, so each refs++ stays paired with
                    // exactly one pin.
                    migo_io::image_cache::global_cache().pin(actual_key);
                }
                self.shared_to_key.insert(shared_id, actual_key.clone());

                for tx in waiters {
                    let _ = tx.send(Ok((actual_key.clone(), shared_id, dims)));
                }
                None
            }
            Err(msg) => {
                if self.alias_to_shared.get(&loader_image_id).copied() == Some(shared_id) {
                    self.alias_to_shared.remove(&loader_image_id);
                }
                self.shared_to_key.remove(&shared_id);
                self.pending_alias_to_key
                    .retain(|_, pending| pending != requested_key);
                for tx in waiters {
                    let _ = tx.send(Err(msg.clone()));
                }
                None
            }
        }
    }

    /// destroy: dec refs; return Some(shared_id) if should actually destroy underlying shared resource
    pub fn try_release_and_get_destroy_rid(&mut self, image_id: u32) -> Option<u32> {
        self.pending_alias_to_key.remove(&image_id);
        let had_alias = self.alias_to_shared.contains_key(&image_id);
        let shared_id = self.alias_to_shared.remove(&image_id).unwrap_or(image_id);

        if let Some(key) = self.shared_to_key.get(&shared_id).cloned() {
            if let Some(entry) = self.by_src.get_mut(&key) {
                if entry.refs > 0 {
                    entry.refs -= 1;
                    // H-5: one alias released → unpin once.  When
                    // entry.refs still > 0 the remaining aliases
                    // keep their own pins, so the io entry
                    // stays live.  When refs hits zero the
                    // final unpin here transitions the entry
                    // to LRU-evictable.
                    migo_io::image_cache::global_cache().unpin(&key);
                }
                if entry.refs == 0 {
                    self.by_src.remove(&key);
                    self.shared_to_key.remove(&shared_id);
                    return Some(shared_id);
                }
                return None;
            }
        }

        if had_alias {
            Some(shared_id)
        } else {
            // not tracked as shared -> destroy caller id directly
            Some(image_id)
        }
    }

    /// Get the source path for an image ID (for texImage2D RGBA lookup).
    #[allow(dead_code)]
    pub fn source_for_image_id(&self, image_id: u32) -> Option<String> {
        let shared_id = self
            .alias_to_shared
            .get(&image_id)
            .copied()
            .unwrap_or(image_id);
        self.shared_to_key
            .get(&shared_id)
            .map(|(path, ..)| path.clone())
    }

    /// Borrow the full cache key for an image ID.
    ///
    /// Borrowed rather than cloned because the only caller is the per-call
    /// texture upload path, which hands the key straight to the decoded-bytes
    /// cache and keeps nothing: an owned copy there is one heap allocation per
    /// `texSubImage2D(image)`. Holding this table's lock across that lookup is
    /// what makes the borrow live long enough, and is the lock order the rest of
    /// this file already takes — see [`ImageCache::drain`].
    pub fn cache_key_for_image_id(&self, image_id: u32) -> Option<&ImageCacheKey> {
        let shared_id = self
            .alias_to_shared
            .get(&image_id)
            .copied()
            .unwrap_or(image_id);
        self.shared_to_key.get(&shared_id)
    }

    /// Resolve a caller-side `image_id` (alias) to the underlying
    /// shared image identifier and its decoded dimensions, if known.
    ///
    /// Returns `None` if no alias has been registered yet (e.g. the
    /// caller invented an `image_id` it never loaded) or if the
    /// underlying load is still in flight.  The dimensions are taken
    /// from the cache entry so callers don't need to round-trip to
    /// the render thread to learn texture extents.
    pub fn shared_for_image_id(&self, image_id: u32) -> Option<(u32, (usize, usize))> {
        let shared_id = self.alias_to_shared.get(&image_id).copied()?;
        let key = self.shared_to_key.get(&shared_id)?;
        let entry = self.by_src.get(key)?;
        Some((shared_id, entry.dims))
    }

    /// Drop every alias this table holds, returning the shared image ids whose
    /// GPU textures the caller is now responsible for destroying.
    ///
    /// The io-side pins go back first.  Each `refs` unit on an entry stands for
    /// one pin taken on the decoded-RGBA cache, and that cache outlives this
    /// table — its entries are context-independent bytes shared with every
    /// other Session — so a pin left behind here would keep those bytes
    /// un-evictable for the life of the process rather than just of this
    /// Session.
    #[must_use = "the returned shared image ids own GPU textures that still need destroying"]
    pub fn drain(&mut self) -> Vec<u32> {
        use std::collections::HashSet;
        let upper_bound = self.by_src.len() + self.alias_to_shared.len();
        let mut seen = HashSet::with_capacity(upper_bound);
        let mut shared_ids: Vec<u32> = Vec::with_capacity(upper_bound);
        for id in self
            .by_src
            .values()
            .map(|e| e.shared_image_id)
            .chain(self.alias_to_shared.values().copied())
        {
            if seen.insert(id) {
                shared_ids.push(id);
            }
        }

        {
            let mut io_cache = migo_io::image_cache::global_cache();
            for (key, entry) in self.by_src.iter() {
                for _ in 0..entry.refs {
                    io_cache.unpin(key);
                }
            }
        }

        self.by_src.clear();
        self.alias_to_shared.clear();
        self.shared_to_key.clear();
        self.loading_map.clear();
        self.pending_alias_to_key.clear();
        shared_ids
    }
}

/// One Session's alias table.
///
/// Handed out as an `Arc` so every op reaches it through the handle its own
/// isolate resolved at bring-up and locks only this Session's `Mutex`.  A
/// `texImage2D` on one game's frame path therefore never waits behind another
/// game's image load, which is what Section 7.3's "no cross-session lock on a
/// per-event path" asks for.
pub type SharedImageCache = Arc<Mutex<ImageCache>>;

/// Per-session registry.
///
/// This table maps a source to a *shared image id*, and such an id names a GPU
/// texture inside one Session's EGL context — each Session builds its own, with
/// no sharing between them.  An id minted by one Session therefore means
/// nothing in another's namespace, which puts this cache in tier one of
/// specification Section 6.5: it must be per-session.  The decoded-RGBA cache
/// one layer below it is the opposite case and stays shared on purpose, because
/// its entries are context-independent bytes under a key that carries the
/// file's real identity.
///
/// The outer `RwLock` is read at isolate bring-up and written at session
/// teardown, and nowhere else: per-event paths hold the `Arc` they resolved at
/// bring-up rather than consulting this map again.
static SESSION_IMAGE_CACHES: LazyLock<RwLock<HashMap<i32, SharedImageCache>>> =
    LazyLock::new(|| RwLock::new(HashMap::new()));

/// Get (or create) the alias table belonging to `host_id`.
///
/// Total by construction, so no caller has to care which of a Session's
/// isolates — the main one or a worker — reaches it first; each keeps the
/// returned `Arc` for as long as it runs.
pub fn image_cache_for_host(host_id: i32) -> SharedImageCache {
    if let Some(existing) = SESSION_IMAGE_CACHES.read().get(&host_id) {
        return existing.clone();
    }
    SESSION_IMAGE_CACHES
        .write()
        .entry(host_id)
        .or_insert_with(|| Arc::new(Mutex::new(ImageCache::new())))
        .clone()
}

/// Hand the registry's own lock to Section 7.3's contention gate.
///
/// The comment on `SESSION_IMAGE_CACHES` claims per-event paths never consult the
/// map, and a claim is not what Section 7.3 accepts: the gate holds this lock and
/// requires a per-event upload to finish anyway. Test-only, so no shipped build
/// can reach past the handle it resolved at bring-up.
#[cfg(test)]
pub(crate) fn session_registry_lock_for_contention_probe()
-> &'static RwLock<HashMap<i32, SharedImageCache>> {
    &SESSION_IMAGE_CACHES
}

/// Whether `host_id` currently has a registered alias table.  Diagnostics and
/// teardown assertions only.
pub fn image_cache_registered(host_id: i32) -> bool {
    SESSION_IMAGE_CACHES.read().contains_key(&host_id)
}

/// Drain `host_id`'s alias table, returning the shared image ids whose textures
/// the caller must destroy on the render thread.
///
/// Registration survives, because the caller is the restart path: the same
/// Session is about to build a fresh isolate that will resolve this same
/// handle.
pub fn drain_shared_image_cache(host_id: i32) -> Vec<u32> {
    let Some(cache) = SESSION_IMAGE_CACHES.read().get(&host_id).cloned() else {
        return Vec::new();
    };
    cache.lock().drain()
}

/// Drop `host_id`'s alias table at session teardown.
///
/// No `DestroyImage` dispatch goes with it and none is needed: the render
/// thread has already joined and its EGL context is gone, so every texture
/// these ids named died with the context.  The io-side pins are the part that
/// does still matter, and [`ImageCache::drain`] releases them.
pub fn unregister_image_cache(host_id: i32) {
    let Some(cache) = SESSION_IMAGE_CACHES.write().remove(&host_id) else {
        return;
    };
    let _ids_naming_textures_of_a_dead_context = cache.lock().drain();
}

#[cfg(test)]
mod tests {
    use super::{ImageCache, ImageCacheKey, make_cache_key};

    /// A requested size names different pixels, not the same pixels at a
    /// different scale, and the decoded-bytes cache stores each in a slot of its
    /// own. A key that forgets the size would make an unsized load and a
    /// `createImageBitmap(img, {resizeWidth})` share one alias — one of them
    /// then draws the other's bitmap.
    ///
    /// Its own guard because the size now rides in the key's own fields rather
    /// than in the path: a key built without them is still a well-formed key,
    /// and every other test in this file uses full-resolution ones.
    #[test]
    fn each_requested_size_gets_a_cache_slot_of_its_own() {
        let unsized_load = make_cache_key("/code/atlas.png", None, None, 4);
        let square = make_cache_key("/code/atlas.png", Some(64), Some(64), 4);
        let tall = make_cache_key("/code/atlas.png", Some(64), Some(128), 4);

        assert_ne!(
            unsized_load, square,
            "a resized request shares the unsized load's slot"
        );
        assert_ne!(square, tall, "two requested sizes share one slot");

        // The decoder writes an unsized decode to the full-resolution slot
        // (`target_*.unwrap_or(0)`), so an alias keyed anywhere else would miss
        // its own bytes on every upload.
        assert_eq!(
            unsized_load,
            migo_io::image_cache::full_res_key("/code/atlas.png".into(), 4),
            "an unsized load must name the slot the decoder writes"
        );
    }

    #[test]
    fn finish_load_merges_converging_actual_keys_without_losing_refs() {
        let mut cache = ImageCache::new();
        let requested_a: ImageCacheKey = ("/code/a.png".into(), 10, 0, 0);
        let requested_b: ImageCacheKey = ("/code/b.png".into(), 11, 0, 0);
        let actual: ImageCacheKey = ("/code/shared.png".into(), 20, 0, 0);

        assert!(matches!(
            cache.begin_load(1, &requested_a),
            super::BeginLoadResult::StartLoading
        ));
        assert!(matches!(
            cache.begin_load(2, &requested_b),
            super::BeginLoadResult::StartLoading
        ));
        cache.register_inflight_alias(1, 100);
        cache.register_inflight_alias(2, 200);

        assert_eq!(
            cache.finish_load(1, 100, &requested_a, &actual, Ok((64, 64))),
            None
        );
        assert_eq!(
            cache.finish_load(2, 200, &requested_b, &actual, Ok((64, 64))),
            Some(200)
        );

        let entry = cache
            .by_src
            .get(&actual)
            .expect("merged entry should exist");
        assert_eq!(entry.shared_image_id, 100);
        assert_eq!(entry.refs, 2);
        assert_eq!(cache.alias_to_shared.get(&1), Some(&100));
        assert_eq!(cache.alias_to_shared.get(&2), Some(&100));
        assert_eq!(cache.shared_to_key.get(&100), Some(&actual));
        assert!(!cache.shared_to_key.contains_key(&200));
    }

    #[test]
    fn bind_alias_existing_ignores_stale_waiters_for_replaced_loads() {
        let mut cache = ImageCache::new();
        let requested_a: ImageCacheKey = ("/code/a.png".into(), 10, 0, 0);
        let requested_b: ImageCacheKey = ("/code/b.png".into(), 11, 0, 0);
        let actual_a: ImageCacheKey = ("/code/a.png".into(), 20, 0, 0);

        cache.begin_load(7, &requested_a);
        let _ = cache.begin_load(7, &requested_b);
        cache.pending_alias_to_key.insert(7, requested_b.clone());
        cache.by_src.insert(
            actual_a.clone(),
            super::SharedImageEntry {
                shared_image_id: 100,
                refs: 1,
                dims: (32, 32),
            },
        );

        cache.bind_alias_existing(7, &requested_a, &actual_a, 100);

        assert_eq!(cache.alias_to_shared.get(&7), None);
        assert_eq!(cache.pending_alias_to_key.get(&7), Some(&requested_b));
        assert_eq!(cache.by_src.get(&actual_a).unwrap().refs, 1);
    }

    #[test]
    fn finish_load_error_clears_loader_and_waiter_bookkeeping() {
        let mut cache = ImageCache::new();
        let requested: ImageCacheKey = ("/code/a.png".into(), 10, 0, 0);

        assert!(matches!(
            cache.begin_load(1, &requested),
            super::BeginLoadResult::StartLoading
        ));
        let _ = cache.begin_load(2, &requested);
        cache.register_inflight_alias(1, 100);

        assert_eq!(
            cache.finish_load(1, 100, &requested, &requested, Err("boom".into())),
            None
        );

        assert!(!cache.alias_to_shared.contains_key(&1));
        assert!(!cache.pending_alias_to_key.contains_key(&2));
        assert!(!cache.loading_map.contains_key(&requested));
    }

    // ── Per-session isolation ───────────────────────────────────────────────
    //
    // The entries here are `src → shared_image_id`, and a shared image id names a
    // GPU texture inside one Session's EGL context.  Reached across Sessions, this
    // table hands game B a name minted in game A's context — a texture B cannot
    // draw and, on destroy, a name whose deletion B has no business ordering.

    use super::{
        BeginLoadResult, drain_shared_image_cache, image_cache_for_host, image_cache_registered,
        unregister_image_cache,
    };

    /// Distinct ids per test, so the shared registry can be asserted without one
    /// test's registrations leaking into another's.
    fn unique_host_pair() -> (i32, i32) {
        use std::sync::atomic::{AtomicI32, Ordering};
        static NEXT: AtomicI32 = AtomicI32::new(7_000);
        let base = NEXT.fetch_add(2, Ordering::Relaxed);
        (base, base + 1)
    }

    struct HostCacheGuard(i32);

    impl Drop for HostCacheGuard {
        fn drop(&mut self) {
            unregister_image_cache(self.0);
        }
    }

    /// Load `key` to completion in `cache` under caller id 1, landing on
    /// `shared_id`.  Mirrors the op's own order: claim, register the in-flight
    /// alias, settle.
    ///
    /// Deliberately asserts nothing.  An earlier version required `begin_load` to
    /// answer `StartLoading` here, which meant three of the tests below died in
    /// this helper under a shared-table mutant and never reached the claim in their
    /// own name — the second session's load simply joined the first's entry. Each
    /// test instead asserts the state it depends on, so a failure lands on the
    /// property it is about.
    fn complete_load(cache: &super::SharedImageCache, key: &ImageCacheKey, shared_id: u32) {
        let mut c = cache.lock();
        let _ = c.begin_load(1, key);
        c.register_inflight_alias(1, shared_id);
        let _ = c.finish_load(1, shared_id, key, key, Ok((64, 64)));
    }

    #[test]
    fn both_isolates_of_one_session_reach_the_same_alias_table() {
        let (id, _) = unique_host_pair();
        let _g = HostCacheGuard(id);
        // A Session runs more than one isolate — the main one and any Worker — and
        // each resolves this handle for itself.  Handing them separate tables would
        // let a texture loaded in one be invisible, and so undestroyable, in the
        // other.
        assert!(std::sync::Arc::ptr_eq(
            &image_cache_for_host(id),
            &image_cache_for_host(id)
        ));
    }

    #[test]
    fn one_sessions_load_does_not_become_another_sessions_alias() {
        let (a_id, b_id) = unique_host_pair();
        let (_ga, _gb) = (HostCacheGuard(a_id), HostCacheGuard(b_id));
        let a = image_cache_for_host(a_id);
        let b = image_cache_for_host(b_id);

        // The same asset, the same caller-side image id: exactly what two games
        // built on the same engine template ask for.
        let key: ImageCacheKey = ("/code/logo.png".into(), 7, 0, 0);
        complete_load(&a, &key, 100);

        // Session B asking for it must be told to load it itself.  A shared table
        // answers `AlreadyLoaded(100)`, and 100 is a texture name in A's context.
        let b_verdict = b.lock().begin_load(1, &key);
        assert!(
            matches!(b_verdict, BeginLoadResult::StartLoading),
            "session B was handed session A's shared image id for {key:?}; that id \
             names a texture in A's EGL context"
        );
        b.lock().register_inflight_alias(1, 200);
        assert_eq!(b.lock().finish_load(1, 200, &key, &key, Ok((64, 64))), None);

        assert_eq!(
            a.lock().shared_for_image_id(1).map(|(id, _)| id),
            Some(100),
            "session A must still resolve to the texture it minted"
        );
        assert_eq!(
            b.lock().shared_for_image_id(1).map(|(id, _)| id),
            Some(200),
            "session B must resolve to its own texture, never A's"
        );
    }

    #[test]
    fn destroying_an_image_in_one_session_spares_the_other_sessions_texture() {
        let (a_id, b_id) = unique_host_pair();
        let (_ga, _gb) = (HostCacheGuard(a_id), HostCacheGuard(b_id));
        let a = image_cache_for_host(a_id);
        let b = image_cache_for_host(b_id);

        let key: ImageCacheKey = ("/code/atlas.png".into(), 3, 0, 0);
        complete_load(&a, &key, 100);
        complete_load(&b, &key, 200);

        // B drops its Image.  The id it hands back for deletion must be its own.
        assert_eq!(b.lock().try_release_and_get_destroy_rid(1), Some(200));
        assert_eq!(
            a.lock().shared_for_image_id(1).map(|(id, _)| id),
            Some(100),
            "session B's destroy released session A's texture"
        );
    }

    #[test]
    fn tearing_down_one_session_leaves_the_others_aliases_reachable() {
        let (a_id, b_id) = unique_host_pair();
        let _gb = HostCacheGuard(b_id);
        let a = image_cache_for_host(a_id);
        let b = image_cache_for_host(b_id);

        let key: ImageCacheKey = ("/code/ui.png".into(), 5, 0, 0);
        complete_load(&a, &key, 100);
        complete_load(&b, &key, 200);

        unregister_image_cache(a_id);
        assert!(
            !image_cache_registered(a_id),
            "a dead session's alias table must not be retained for process life"
        );
        assert_eq!(
            b.lock().shared_for_image_id(1).map(|(id, _)| id),
            Some(200),
            "one session's teardown discarded another live session's aliases"
        );

        // A later session reusing the id inherits nothing: every name the previous
        // one held belonged to an EGL context that no longer exists.
        let _ga = HostCacheGuard(a_id);
        assert!(
            image_cache_for_host(a_id)
                .lock()
                .shared_for_image_id(1)
                .is_none()
        );
        drop(a);
    }

    #[test]
    fn restarting_one_session_drains_only_its_own_textures() {
        let (a_id, b_id) = unique_host_pair();
        let (_ga, _gb) = (HostCacheGuard(a_id), HostCacheGuard(b_id));
        let a = image_cache_for_host(a_id);
        let b = image_cache_for_host(b_id);

        let key: ImageCacheKey = ("/code/tiles.png".into(), 11, 0, 0);
        complete_load(&a, &key, 100);
        complete_load(&b, &key, 200);

        // The restart path dispatches a destroy for every id this returns, so an
        // id belonging to another game would black out its live textures.
        assert_eq!(
            drain_shared_image_cache(a_id),
            vec![100],
            "the restart drain returned an id this session does not own"
        );
        assert_eq!(
            b.lock().shared_for_image_id(1).map(|(id, _)| id),
            Some(200),
            "one session's restart ordered another session's textures destroyed"
        );
        assert!(
            image_cache_registered(a_id),
            "a restart must keep the registration the new isolate will resolve"
        );
        assert!(a.lock().shared_for_image_id(1).is_none());
    }

    #[test]
    fn a_torn_down_session_releases_the_decoded_bytes_it_had_pinned() {
        let (a_id, _) = unique_host_pair();
        // Unique path: the decoded-bytes cache this asserts against is shared with
        // every other test in this binary.
        let key: ImageCacheKey = (format!("/code/pinned-{a_id}.png"), 13, 0, 0);

        complete_load(&image_cache_for_host(a_id), &key, 100);
        assert_eq!(
            migo_io::image_cache::global_cache().pin_count(&key),
            1,
            "a live alias must pin the decoded bytes it draws from"
        );

        unregister_image_cache(a_id);
        assert_eq!(
            migo_io::image_cache::global_cache().pin_count(&key),
            0,
            "the pin outlived the session that took it, so these bytes can never be \
             evicted again -- the decoded cache is deliberately not cleared on \
             teardown, which is what makes the leak permanent"
        );
    }
}

// ── Section 7.3: no cross-session lock on a per-event path ──────────────────

#[cfg(test)]
mod cross_session_contention {
    use super::{
        ImageCacheKey, image_cache_for_host, make_cache_key,
        session_registry_lock_for_contention_probe, unregister_image_cache,
    };
    use migo_contention_probe::{PATIENCE, PerEventPath, assert_completes_while_locked};

    /// Section 7.3, on the upload path's reach for the per-session registry.
    ///
    /// `SESSION_IMAGE_CACHES` maps every live Session to its alias table, so it is
    /// shared beyond any one game. The design says per-event paths never consult
    /// it — they hold the `Arc` resolved once at isolate bring-up — and until now
    /// that was a comment. A comment cannot fail when someone adds a lookup, and
    /// the lookup would even work: it returns the right table, just after queueing
    /// behind every other Session's bring-up and teardown, on a path that runs per
    /// `texSubImage2D`.
    ///
    /// Contention is manufactured rather than waited for, so this also fails for
    /// an *uncontended* acquisition — the case a load test cannot see.
    #[test]
    fn a_texture_upload_does_not_queue_behind_the_session_registry() {
        let host_id = 8_100;
        let _guard = HostCacheGuard(host_id);

        // Resolved at bring-up, exactly as an isolate does, before the registry is
        // locked out from under it.
        let aliases = image_cache_for_host(host_id);
        let key: ImageCacheKey = make_cache_key("/code/contended.png", None, None, 3);
        {
            let mut cache = aliases.lock();
            let _ = cache.begin_load(1, &key);
            cache.register_inflight_alias(1, 0x6000_0001);
            let _ = cache.finish_load(1, 0x6000_0001, &key, &key, Ok((8, 8)));
        }

        let expected = key.clone();
        let resolved = assert_completes_while_locked(
            PerEventPath {
                path: "texture upload resolving its alias table",
                shared_lock: "SESSION_IMAGE_CACHES (every live Session's alias table)",
                patience: PATIENCE,
            },
            session_registry_lock_for_contention_probe(),
            move || aliases.lock().cache_key_for_image_id(1).cloned(),
        );

        assert_eq!(
            resolved,
            Some(expected),
            "the fixture must actually resolve the alias, or a completion proves \
             nothing about the path"
        );
    }

    struct HostCacheGuard(i32);

    impl Drop for HostCacheGuard {
        fn drop(&mut self) {
            unregister_image_cache(self.0);
        }
    }
}
