// The checks an audio command makes before it is sent, against the answers the
// embedded op gives.
//
// A command has no answer, so the producer refuses a malformed call itself,
// before sending, with the class and words the embedded op throws
// (src/audio.mjs). fixtures/audio-check-answers.json is what those checks
// answer in Rust (`migo_services::audio`, regenerated by
// `MIGO_AUDIO_CHECKS_BLESS=1 cargo test -p migo-services the_producer_s_command_checks`);
// this runs the producer's checks over the same cases and requires the same
// answer for each -- nothing thrown, or an AudioError with the same message.
//
// Strings are checked by their UTF-8 length, which is what the Rust check
// reads. So each length is built three ways -- one byte per unit, two, and lone
// surrogates, which the op's `#[string]` conversion turns into three-byte
// U+FFFD -- and the producer has to count every one as Rust would.
//
// Run:  node test/audio-checks.test.mjs
// Gate: scripts/test-frame-wire-js-encoder.sh

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import {
  AUDIO_CONTROL_STRING_LIMIT,
  CLASS_AUDIO_ERROR,
  checkControlString,
  checkEncodedAudioBytes,
  checkIirCoefficients,
  checkLoopPoints,
  checkOptionalDuration,
  checkScheduledTime,
  checkWaveShaperCurveBytes,
  utf8Length,
} from "../src/audio.mjs";

const answers = JSON.parse(readFileSync(new URL("./fixtures/audio-check-answers.json", import.meta.url), "utf8"));

const number = (text) =>
  ({ NaN: NaN, Infinity: Infinity, "-Infinity": -Infinity })[text] ?? Number(text);

let checked = 0;
function expect(label, error, run) {
  checked += 1;
  let thrown = null;
  try {
    run();
  } catch (caught) {
    thrown = caught;
  }
  if (error === null) {
    assert.equal(thrown, null, `${label}: threw ${thrown} where the op accepts`);
    return;
  }
  assert.ok(thrown !== null, `${label}: accepted where the op throws ${JSON.stringify(error)}`);
  assert.equal(thrown.name, CLASS_AUDIO_ERROR, `${label}: class`);
  assert.equal(thrown.message, error, `${label}: message`);
}

assert.equal(answers.class, CLASS_AUDIO_ERROR);
assert.equal(answers.control_string_limit, AUDIO_CONTROL_STRING_LIMIT);

for (const { name, value, error } of answers.scheduled_time) {
  expect(`${name} = ${value}`, error, () => checkScheduledTime(name, number(value)));
}
for (const { value, error } of answers.optional_duration) {
  expect(`duration = ${value}`, error, () => checkOptionalDuration(number(value)));
}
for (const { start, end, error } of answers.loop_points) {
  expect(`loop ${start}..${end}`, error, () => checkLoopPoints(number(start), number(end)));
}
for (const { feedforward, feedback, error } of answers.iir_coefficients) {
  expect(`iir ${feedforward}/${feedback}`, error, () =>
    checkIirCoefficients(feedforward.map(number), feedback.map(number)),
  );
}
for (const { bytes, error } of answers.wave_shaper_curve_bytes) {
  expect(`curve of ${bytes} bytes`, error, () => checkWaveShaperCurveBytes(bytes));
}
for (const { bytes, error } of answers.encoded_audio_bytes) {
  expect(`encoded audio of ${bytes} bytes`, error, () => checkEncodedAudioBytes(bytes));
}

/** Strings whose UTF-8 form, as the op converts them, is `bytes` long. */
function stringsOf(bytes) {
  const out = [["ascii", "x".repeat(bytes)]];
  if (bytes % 2 === 0) out.push(["two-byte", "é".repeat(bytes / 2)]);
  if (bytes % 3 === 0) out.push(["lone surrogates", "\ud800".repeat(bytes / 3)]);
  if (bytes % 4 === 0) out.push(["astral", "\u{1f600}".repeat(bytes / 4)]);
  return out;
}

for (const { field, utf8_bytes: bytes, error } of answers.control_string) {
  for (const [shape, text] of stringsOf(bytes)) {
    assert.equal(utf8Length(text), bytes, `${shape} string of ${bytes} bytes`);
    expect(`${field}, ${shape}, ${bytes} bytes`, error, () => checkControlString(field, text));
  }
}

// The count agrees with what goes on the wire: the service writer's
// TextEncoder, which is how the host receives the string.
const encoder = new TextEncoder();
for (const text of ["", "abc", "éé", "\ud800", "a\ud800b", "\udc00", "\u{1f600}", "😀\ud83d"]) {
  assert.equal(utf8Length(text), encoder.encode(text).byteLength, JSON.stringify(text));
}

console.log(`audio checks: ${checked} answers agree with migo_services::audio`);
