// A CSS colour, as the producer reads it against the host's own parser.
//
// The engine's Canvas2D code encodes the forms it is sure of and hands the rest
// to `op_set_fill_style`, whose Rust body is the authority
// (`context2d.rs::parse_color_string`). On this lane that op is the producer's,
// so its port has to answer the same thing -- including for the colours a game
// really writes and the engine abstains from, like `rgb( 1 , 2 , 3 )`.
//
// fixtures/canvas2d-color-answers.json is the corpus both Rust tests use and
// what the Rust parser makes of each entry, regenerated by
// `MIGO_COLOUR_ANSWERS_BLESS=1 cargo test -p migo-runtime-v8 --lib
// the_producer_s_colour_parser`.
//
// Run:  node test/canvas2d-color.test.mjs
// Gate: scripts/test-frame-wire-js-encoder.sh

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import { colorRecordWords, parseColorString } from "../src/canvas2d-color.mjs";

const { colours } = JSON.parse(
  readFileSync(new URL("./fixtures/canvas2d-color-answers.json", import.meta.url), "utf8"),
);

assert.ok(colours.length > 500, `the corpus is ${colours.length} colours; it covers more than that`);

// A name the engine's own table answers never reaches this op: the producer
// runs that same JavaScript, and `the_named_colours_agree_name_for_name` is
// what keeps the two tables identical. The port is required on everything else.
const reaching = colours.filter((colour) => !colour.named);
assert.ok(
  colours.length - reaching.length > 100,
  "the corpus should carry the named colours too, so one corpus serves both checks",
);

let failures = 0;
for (const { text, rgba } of reaching) {
  const got = parseColorString(text);
  try {
    assert.deepEqual(got, rgba);
  } catch {
    failures += 1;
    if (failures <= 10) console.log(`  FAIL ${JSON.stringify(text)}: ${got} where Rust reads ${rgba}`);
  }
}
if (failures > 0) {
  console.log(`FAIL: ${failures} of ${reaching.length} colours differ`);
  process.exit(1);
}

// The record carries the four floats as their bits, and the parser's channels
// are k/255 exactly.
const bitsOf = (text) => {
  const floats = new Float32Array(4);
  new Uint32Array(floats.buffer).set(colorRecordWords(text));
  return Array.from(floats);
};
assert.deepEqual(bitsOf("#ff0000"), [1, 0, 0, 1]);
assert.deepEqual(bitsOf("rgba(0,0,0,0)"), [0, 0, 0, 0]);
assert.deepEqual(bitsOf("rgb( 1 , 2 , 3 )"), [1 / 255, 2 / 255, 3 / 255, 1].map(Math.fround));

console.log(`canvas2d colours: ${reaching.length} answers agree with parse_color_string`);
