// A socket event, as the host writes it and this producer rebuilds it: the
// WebSocket's four and the raw sockets' five.
//
// A WebSocket cannot ride the record-and-replay harness the fetch calls do: the
// replay would need a server, and every address a test server could listen on
// is one the address filter refuses -- which is that filter working. So the one
// thing the two halves must agree about is the event's shape, and
// fixtures/ws-event-answers.json is what the host writes for each kind
// (`service_network.rs`, regenerated by `MIGO_WS_EVENTS_BLESS=1 cargo test -p
// migo-core --no-default-features --features external-frames
// the_producer_s_socket_events`).
//
// This puts each of those through `wsEvent` and requires the object the
// engine's `WebSocket` facade reads: a message carries `dataStr` or `dataBin`
// and never both, an error carries `errMsg`, a close carries its code and
// reason.
//
// Run:  node test/socket-events.test.mjs
// Gate: scripts/test-frame-wire-js-encoder.sh

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import { tcpEvent, udpEvent, wsEvent } from "../src/network.mjs";

const { events, tcp, udp } = JSON.parse(
  readFileSync(new URL("./fixtures/ws-event-answers.json", import.meta.url), "utf8"),
);

/** The host's bytes arrive as a Uint8Array; the fixture writes them as numbers. */
const asWire = (wire) => wire.map((field) => (Array.isArray(field) ? Uint8Array.from(field) : field));

const expected = {
  text: { type: "message", dataStr: "hello", isBinary: false },
  binary: { type: "message", dataBin: Uint8Array.of(0, 127, 255), isBinary: true },
  error: { type: "error", errMsg: "connection reset" },
  close: { type: "close", code: 1006, reason: "" },
  "close with a reason": { type: "close", code: 1000, reason: "bye" },
};

assert.deepEqual(
  events.map((event) => event.name).sort(),
  Object.keys(expected).sort(),
  "the fixture and this test cover the same events",
);

for (const { name, wire } of events) {
  const rebuilt = wsEvent(asWire(wire));
  assert.deepEqual(rebuilt, expected[name], `${name}: the facade's object`);
  // A message carries one payload, never both: the facade reads `isBinary` and
  // then one field, and an event with both would make the other silently dead.
  if (rebuilt.type === "message") {
    assert.equal("dataStr" in rebuilt, !rebuilt.isBinary, `${name}: dataStr`);
    assert.equal("dataBin" in rebuilt, rebuilt.isBinary, `${name}: dataBin`);
  }
}

// The raw sockets' events, in the same tagged shape.
const endpoint = {
  remoteAddress: "93.184.216.34",
  remoteFamily: "IPv4",
  remotePort: 9000,
  localAddress: "10.0.0.2",
  localFamily: "IPv4",
  localPort: 51000,
};
const tcpExpected = {
  message: { type: "message", data: Uint8Array.from([112, 111, 110, 103]), ...endpoint },
  error: { type: "error", errMsg: "connection reset" },
  close: { type: "close" },
};
const udpExpected = {
  message: { type: "message", data: Uint8Array.from([112, 105, 110, 103]), size: 4, ...endpoint },
  error: { type: "error", errMsg: "no route to host" },
};

for (const [kind, rows, rebuild, wanted] of [
  ["tcp", tcp, tcpEvent, tcpExpected],
  ["udp", udp, udpEvent, udpExpected],
]) {
  assert.deepEqual(
    rows.map((row) => row.name).sort(),
    Object.keys(wanted).sort(),
    `${kind}: the fixture and this test cover the same events`,
  );
  for (const { name, wire } of rows) {
    assert.deepEqual(rebuild(asWire(wire)), wanted[name], `${kind} ${name}: the facade's object`);
  }
}

console.log(
  `socket events: ${events.length + tcp.length + udp.length} shapes agree with service_network.rs`,
);
